# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.name = 'aws_s3'
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.provision "shell", path: "provisioning.py"
  config.vm.network "private_network", ip: "192.168.123.3"
end